on:
  push

jobs:
  tsc-check:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update -y && sudo apt-get install -y curl
      - run: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash,
      - run: source ~/.bashrc
      - run: nvm install 16.16.0
      - run: npm install ts-node
      - run: tsc --clean .

