on:
  push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: npm install
      - run: npm run ts
      - run: npm run lint
  release:
    needs: [check]
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/rc-0.0.')
    steps:
      - run: sudo apt-get update -y && sudo apt-get install -y snapd && sudo snap install jo && pip install yandex_tracker_client
      - uses: actions/checkout@v3
      - run: >
          jo \
            org_id="${{ secrets.TRACKER_ORG_ID }}" \
            token="${{ secrets.TRACKER_TOKEN }}" \
            ticket_id="${{ secrets.TRACKER_TICKET_ID }}" \
            action=update_ticket \
            update.summary="$(date +%d.$m.$Y) - tag" \
            update.description=description | xargs -0 python3 scripts/sync_with_tracker.py

